judge:
  _target_: lerobot.utils.action_predictability.MLP
  input_dim: 18
  hidden_dim: 512
  output_dim: 3

reye_dest: /nasa/team-space/artifacts/predictions/lerobot

expert:
  train_run: train_judge_expert_policy_t_10

learner:
  train_run: train_judge_learned_policy_t_10