judge:
  _target_: lerobot.utils.action_predictability.MLP
  input_dim: 18
  hidden_dim: 512
  output_dim: 3
  nr_hidden_layers: 0

reye_dest: /nasa/team-space/artifacts/predictions/lerobot

expert:
  train_run: expert_smlvla_t_10
  num_epochs: 10
  batch_size: 2048
  lr: 1e-3
  weight_decay: 0

learner:
  train_run: learner_smlvla_t_10
  num_epochs: 10
  batch_size: 2048
  lr: 1e-3
  weight_decay: 0