models:
  bfloat16:
    _target_: polars.read_parquet
    source: /nasa/team-space/artifacts/predictions/lerobot/denoising/bfloat16x10//policy_smolvla-seed_1000-dataset_yaak-ai_L2D-560000:v3/same_noise/results.parquet
  float16:
    _target_: polars.read_parquet
    source: /nasa/team-space/artifacts/predictions/lerobot/denoising/bfloat16x5/policy_smolvla-seed_1000-dataset_yaak-ai_L2D-560000:v3/same_noise/results.parquet

drive_column: batch/meta/input_id